pollstyr/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.models import User
app_name = 'app'
# from django.contrib import admin
# from django.urls import path

urlpatterns = [
    
    path('', views.home,name='home'),
    path('index',views.index,name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path("register",views.register, name='register'),
    path("login",views.login, name='login'),
    path("logout",views.logout, name='logout'),
    path("voter",views.voter, name='voter')
]

pollstyr/pro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

pollstyr/app/models.py
from django.db import models
from django.contrib.auth.models import User


class Question (models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date publisher')

    def __str__(self):
        return self.question_text


class Choice (models.Model):
    # if qustion is deleted then automaticaly choices also deleted
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Vote (models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    vote= models.ForeignKey(User, on_delete=models.CASCADE)

pollstyr/app/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, reverse

from .models import Question, Choice, Vote
from django.contrib.auth.models import User, auth

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth


def home(request):
    return render(request, 'home.html')


def index(request):
    latest_question_list = Question.objects.all()
    for qstn in latest_question_list:
        print(qstn.question_text)
    context = {'latest_question_list': latest_question_list}
    return render(request, 'index.html', context)

# Show specific question and choice


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExits:
        raise Http404("Question does not exist")
    return render(request, 'detail.html', {'question': question})


# get question and display results

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'results.html', {'question': question})

# vote


def vote(request, question_id):
    # if request.user.is_authenticated:
    #     question = get_object_or_404(Question, pk=question_id)
    #     try:
    #         selected_choice = question.choice_set.get(pk=request.POST['choice'])
    #     except (KeyError, Choice.DoesNotExist):
    #         return render(request, 'detail.html', {'question': question, 'error_message': "You did not select a choice", })
    #     else:
    #         selected_choice.votes += 1
    #         selected_choice.save()
    #         return HttpResponseRedirect(reverse('app:results', args=(question_id,)))
    # else:
    #     print("Please login")
    #     return redirect('app:home')
        
    question = get_object_or_404(Question, pk=question_id)
    
    
    if Vote.objects.filter(question=question,vote=request.user).exists():
        messages.error(request,"Already Voted on this Question")
        return redirect('app:index')
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'detail.html', {'question': question, 'error_message': "you did not select a choice", })
    
    else:
        
        selected_choice.votes += 1
        selected_choice.save()
        v= Vote(question=question,vote=request.user)
        v.save()
        
        return HttpResponseRedirect(reverse('app:results', args=(question_id,)))



# Login


def register(request):
    if request.method == 'POST':
        # name = request.POST.get('name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        conformPassword = request.POST.get('conformpassword')
        user = User.objects.create_user(
            username=username, email=email, password=password)
        user.save()
        print('user created')
        return redirect('/login')
    else:
        return render(request, 'register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = auth.authenticate(username=username, password=password)
        print('login successfull')
        if user is not None:
            auth.login(request, user)
            return redirect('app:index')
        else:
            message.info(request, 'Invalid credentials')
            return redirect('app:login')
    else:
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

def voter(request):
    voter = Vote.objects.all()
    return render(request,'showvoter.html',{'voter':voter})

pollstyr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Pollstar{% block title %}{% endblock %} </title>
</head>
<body>
    
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

pollstyr/templates/detail.html
{% extends 'base.html'%} 
{% block content %}
    
    <a class="btn btn-secondary btn-sm mb-3 " href="{% url 'app:index' %}">Back to polls</a>
    <h1 class="text-center mb-3"> {{ question.question_text}} </h1>
{% if error_message %}
<p class="alert alert-denger">
    <strong> {{ error_message }} </strong>
</p>
{% endif %}

<form action="{% url 'app:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input type="radio" name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
        class="form-check-input"
        />
        <lable for="choice{{ forloop.counter }}"> {{ choice.choice_text}} </lable>

    </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btnblock mt-4"/>
</form>

    {% endblock %}

pollstyr/templates/home.html
<h1>Welcome to Pollapp</h1>
     
    <a href="{% url 'app:login' %}">Login</a>
    <a href="{% url 'app:register' %}">Register</a>

pollstyr/templates/index.html
{% extends 'base.html'%}
{% block content %}

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

    <h1 class="text-center mb-3">List of Polls </h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
        <div class="card mb-3">
            <div class="card-body">
                <p class="lead">{{ question.question_text }}</p>
                <a href=" {% url 'app:detail' question.id %} " class="btn btn-primary btn-sm">Vote Now</a>
                <a href=" {% url 'app:results' question.id %} " class="btn btn-secondary btn-sm">Results</a>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p>No polls available</p>
    {% endif %}
{% endblock %}

pollstyr/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <form action="login" method="POST">
        {% csrf_token %}

        <input type="text" name="username" placeholder="Enter UserName"><br>
        <input type="password" name="password" placeholder="Enter password"><br>
        <input type="SUBMIT">
    </form>
</body>
</html>

pollstyr/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registeration</title>
</head>
<body>
    <form action="register" method="POST">
        {% csrf_token %}

        <input type="text" name="username" placeholder="Enter UserName"><br>
        <input type="email" name="email" placeholder="Enter Email"><br>
        <input type="password" name="password" placeholder="Enter password"><br>
        <input type="password" name="conformpassword" placeholder="ConformPassword"><br>
        <input type="SUBMIT">
    </form>
</body>
</html>

pollstyr/templates/results.html
{% extends 'base.html'%}
{% block content %}
<h1 class="mb-5 text-center"> {{ question.question_text }} </h1>

<ul class="list-group mb-5">
   {% for choice in question.choice_set.all %}
   <li class="list-group-item">
      {{ choice.choice_text }} <span class="badge badge-success float-right">{{choice.votes}} vote
         {{ choice.votes | pluralize }}</span>
   </li>
   {% endfor %}
</ul>
<a class="btn btn-secondary" href="{% url 'app:index' %}">Back to polls</a>
<a class="btn btn-dark" href="{% url 'app:detail' question.id %}">Vote Again</a>
<a class="btn btn-secondary" href="{% url 'app:home' %}">Logout</a>
{% endblock %}

pollstyr/templates/showvoter.html
{% extends 'base.html'%}
{% block content %}

<div class="container">
  <h2>Basic Table</h2>
  <p>List of user who voted polls question:</p>            
  <table class="table">
    <thead>
      <tr>
        <th>Question Voter</th>
        <th>User</th>
      </tr>
    </thead>
    {% for Vote in voter %}
    <tbody>
      <tr>
        <td>{{ Vote.question}}</td>
        <td>{{ Vote.vote }}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>
{% endblock %}